language: node_js

node_js:
   - "6"
services:
  - mongodb

cache:
  directories:
    - $HOME/.meteor
    - $HOME/.npm

before_cache:
  - rm -f $HOME/.meteor/log/*.log
  - rm -rf node_modules

before_install:
  # Download Meteor - Keep in mind that you need
  # to remove your travis cache to get meteor updates
  - PATH=$PATH:$HOME/.meteor
  - if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi

install:
  # Install dependencies
  - git clean -fXd
  - npm install -g phantomjs-prebuilt rollup@^0.37.0 tslint@^4.0.0 typescript@^2.0.10
  - meteor npm install

script:
 #- meteor npm test
  #- echo "build OK"

 after_success:
 
  - bash <(curl -s https://codecov.io/bash);

notifications:
  slack: otoktons:a5eW914L1Zzfkfu7hiEWoiZ1
